<?php

include_once('npm_datasource.features.inc');


/**
 * Implements hook_views_data().
 *
 * Indicates custom field handlers for views.
 */
// function npm_datasource_views_data_alter(&$data) {
//   // dsm('npm_datasource_views_data_alter');
//   // dsm($data);
//   $data['npm_datasource']['field_partner_organizations'] = array(
//     'field' => array(
//       'title' => t('Partner Organizations'),
//       'help' => t('Display names and paths to partner organizations.'),
//       'handler' => 'views_handler_field_partner_organizations',
//     ),
//   );
// }


/**
* Implementation of hook_action_info().
*/
function npm_datasource_action_info() {
  return array(
    'npm_datasource_update_mongo_action' => array(
      'description' => t('Updates the Mongo database with current drupal content'),
      'type' => 'node',
      'configurable' => FALSE,
      'hooks' => array('any' => TRUE),
      ),
  );
}

/**
* Implementation of a Drupal action.
* Updates the Mongo database with current drupal content
*/
function npm_datasource_update_mongo_action(&$object, $context = array()) {
  npm_datasource_update_mongo($object, $context);
}

function npm_datasource_update_mongo(&$object, $context) {
  // dsm($object);
  // dsm($context);
  
  include_once('../api/loaddata_functions.inc');
  include_once('../../authentication/newplaymap_authentication.php');
  connectMongo(false);
  
  $domain = $_SERVER['HTTP_HOST'];
  $drupal_base_path = base_path();
  $id = $object->nid;
  
  switch ($context['hook']) {
    // Update a specific piece of content
    case 'nodeapi':
      switch ($object->type) {
        case 'artist':
          loadArtists($m, $mongo_database, $domain, $drupal_base_path, $id);
        break;
        case 'event':
          loadEvents($m, $mongo_database, $domain, $drupal_base_path, $id);
          loadPlays($m, $mongo_database, $domain, $drupal_base_path, $object->field_related_play[0]['nid']);
        break;
        case 'organization':
          loadOrganizations($m, $mongo_database, $domain, $drupal_base_path, $id);
        break;
        case 'play':
          loadPlays($m, $mongo_database, $domain, $drupal_base_path, $id);
          // Load all events for this play also
          loadEvents($m, $mongo_database, $domain, $drupal_base_path, 'all/' . $id);
        break;
      }
    break;
    // Update everything on cron
    case 'cron':
      global $m;
      global $mongo_database;

      // Events needs to run first because Artists uses it for related organization info
      loadEvents($m, $mongo_database, $domain, $drupal_base_path, FALSE, TRUE);

      loadArtists($m, $mongo_database, $domain, $drupal_base_path, FALSE, TRUE);
      loadPlays($m, $mongo_database, $domain, $drupal_base_path, FALSE, TRUE);
      loadOrganizations($m, $mongo_database, $domain, $drupal_base_path, FALSE, TRUE);
    break;
  }
  
}
