<?php

include_once('npm_datasource.features.inc');

/**
 * Implementation of hook_menu()
 */
function npm_datasource_menu() {
  $items = array();
  $items['admin/content/update-mongo'] = array(
    'access arguments'  => array('administer site configuration'),
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('npm_datasource_admin_update_mongo_form'),
    'title'             => 'Update Mongo',
  );
  
  return $items;
}

function npm_datasource_admin_update_mongo_form() {
  $form['update_mongo'] = array(
    '#type' => 'submit',
    '#value' => t('Update Mongo'),
    '#submit' => array('npm_datasource_admin_update_mongo'),
  );

  return system_settings_form($form);
}

function npm_datasource_admin_update_mongo($form, &$form_state) {
  dsm('npm_datasource_admin_update_mongo');
  $batch = array(
    'operations' => array(
      array('npm_datasource_admin_update_mongo_process', array())
      ),
    'finished' => 'npm_datasource_admin_update_mongo_finished',
    'title' => t('Update New Play Map Mongo Database'),
    'init_message' => t('Starting database update.'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('Mongo Update has encountered an error.'),
  );
  batch_set($batch);
}

function npm_datasource_admin_update_mongo_process(&$context) {
  include_once('../api/loaddata_functions.inc');
  include_once('../../authentication/newplaymap_authentication.php');
  connectMongo(false);

  if (!isset($context['sandbox']['progress'])) {
    // Build list of nids
    // Put events first
    $events = array();
    $events_query = db_query('SELECT nid, type FROM {node} WHERE type = "event"');
    while ($row = db_fetch_array($events_query)) {
      $events[] = $row;
    }
    
    $other_content = array();
    $other_content_query = db_query("SELECT nid, type FROM {node} WHERE type = 'artist' OR type = 'organization' OR type = 'play'");
    while ($row = db_fetch_array($other_content_query)) {
      $other_content[] = $row;
    }

    $all_content = array_merge($events, $other_content);

    $context['sandbox']['progress'] = 0;
    $context['sandbox']['current_node'] = 0;
    $context['sandbox']['max'] = count($all_content);
  }

  $i = 0;
  foreach ($all_content as $content) {
    $domain = $_SERVER['HTTP_HOST'];
    $drupal_base_path = base_path();
    switch ($content['type']) {
      case 'event':
        loadEvents($m, $mongo_database, $domain, $drupal_base_path, $content['nid']);
      break;
      case 'organization':
        loadOrganizations($m, $mongo_database, $domain, $drupal_base_path, $content['nid']);
      break;
      case 'artist':
        loadArtists($m, $mongo_database, $domain, $drupal_base_path, $content['nid']);
      break;
      case 'play':
        loadPlays($m, $mongo_database, $domain, $drupal_base_path, $content['nid']);
      break;
    }
    // Here we actually perform our processing on the current node.
    // $node = node_load($row['nid'], NULL, TRUE);
    // dsm($node->title);

    // Store some result for post-processing in the finished callback.
    $context['results'][] = $content['nid'];

    // Update our progress information.
    $context['sandbox']['progress']++;
    $context['sandbox']['current_node'] = $i;
    $i++;
    $context['message'] = t('Now processing: %type', array('%type' => $content['type']));
  }
  dsm('sandbox progress: ' . $context['sandbox']['progress']);
  dsm('sandbox max: ' . $context['sandbox']['max']);
  // Inform the batch engine that we are not finished,
  // and provide an estimation of the completion level we reached.
  if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }
}

function npm_datasource_admin_update_mongo_finished($success, $results, $operations) {
  if ($success) {
    // Here we do something meaningful with the results.
    $message = count($results) .' processed.';
    $message .= theme('item_list', $results);
  }
  else {
    // An error occurred.
    // $operations contains the operations that remained unprocessed.
    $error_operation = reset($operations);
    $message = t('An error occurred while processing %error_operation with arguments: @arguments', array('%error_operation' => $error_operation[0], '@arguments' => print_r($error_operation[1], TRUE)));
  }
  drupal_set_message($message);
}

/**
* Implementation of hook_action_info().
*/
function npm_datasource_action_info() {
  return array(
    'npm_datasource_update_mongo_action' => array(
      'description' => t('Updates the Mongo database with current drupal content'),
      'type' => 'node',
      'configurable' => FALSE,
      'hooks' => array('any' => TRUE),
      ),
    'npm_datasource_delete_mongo_action' => array(
      'description' => t('Deletes records from the Mongo database'),
      'type' => 'node',
      'configurable' => FALSE,
      'hooks' => array('any' => TRUE),
      ),
  );
}

/**
* Implementation of a Drupal action.
* Updates the Mongo database with current drupal content
*/
function npm_datasource_update_mongo_action(&$object, $context = array()) {
  npm_datasource_update_mongo($object, $context);
}

function npm_datasource_update_mongo(&$object, $context) {
  // dsm($object);
  // dsm($context);
  
  include_once('../api/loaddata_functions.inc');
  include_once('../../authentication/newplaymap_authentication.php');
  connectMongo(false);
  
  $domain = $_SERVER['HTTP_HOST'];
  $drupal_base_path = base_path();
  $id = $object->nid;
  
  switch ($context['hook']) {
    // Update a specific piece of content
    case 'nodeapi':
      switch ($object->type) {
        case 'artist':
          loadArtists($m, $mongo_database, $domain, $drupal_base_path, $id);
        break;
        case 'event':
          // Update this event
          loadEvents($m, $mongo_database, $domain, $drupal_base_path, $id);

          // Update the play in case a play was created using the add event form
          loadPlays($m, $mongo_database, $domain, $drupal_base_path, $object->field_related_play[0]['nid']);

          // Update the organization in case a play was created using the add event form
          // Update the partner organizations to help with related lists
          $all_organization_nids = $object->field_related_theater[0]['nid'];
          foreach ($object->field_partner_org as $partner_organization) {
            if (!empty($partner_organization['nid'])) {
              $all_organization_nids .= '+' . $partner_organization['nid'];
            }
          }
          loadOrganizations($m, $mongo_database, $domain, $drupal_base_path, $all_organization_nids);

          // Add related artist from play
          $play = node_load($object->field_related_play[0]['nid']);
          loadArtists($m, $mongo_database, $domain, $drupal_base_path, $play->field_artist[0]['nid']);
        break;
        case 'organization':
          loadOrganizations($m, $mongo_database, $domain, $drupal_base_path, $id);
        break;
        case 'play':
          loadPlays($m, $mongo_database, $domain, $drupal_base_path, $id);
          // Load all events for this play also
          loadEvents($m, $mongo_database, $domain, $drupal_base_path, 'all/' . $id);
        break;
      }
    break;
    // Update everything on cron
    case 'cron':
      global $m;
      global $mongo_database;

      // Events needs to run first because Artists uses it for related organization info
      loadEvents($m, $mongo_database, $domain, $drupal_base_path, FALSE, TRUE);

      loadArtists($m, $mongo_database, $domain, $drupal_base_path, FALSE, TRUE);
      loadPlays($m, $mongo_database, $domain, $drupal_base_path, FALSE, TRUE);
      loadOrganizations($m, $mongo_database, $domain, $drupal_base_path, FALSE, TRUE);
    break;
  } 
}

/**
* Implementation of a Drupal action.
* Deletes records from the Mongo database
*/
function npm_datasource_delete_mongo_action(&$object, $context = array()) {
  npm_datasource_delete_mongo($object, $context);
}

function npm_datasource_delete_mongo(&$object, $context) {
  include_once('../api/loaddata_functions.inc');
  include_once('../../authentication/newplaymap_authentication.php');
  connectMongo(false);
  
  $id = $object->nid;
  
  switch ($context['hook']) {
    // Update a specific piece of content
    case 'nodeapi':
      switch ($object->type) {
        case 'artist':
          // Delete the artist record
          // deleteArtists($m, $mongo_database, $id);
          
          // @TODO: Figure out what other content to update
        break;
        case 'event':
          // Delete the event record
          deleteEvents($m, $mongo_database, $id);
          
          // @TODO: Figure out what other content to update
        break;
        case 'organization':
          // Delete the organization record
          // deleteOrganizations($m, $mongo_database, $id);
          
          // @TODO: Figure out what other content to update
        break;
        case 'play':
          // Delete the play record
          // deletePlays($m, $mongo_database, $id);
          
          // @TODO: Figure out what other content to update
        break;
      }

      // Redirect to the map
      $domain = $_SERVER['HTTP_HOST'];
      $drupal_base_path = base_path();
      $path_to_map = str_replace("/participate/", "", $drupal_base_path);
      drupal_goto('http://' . $domain . $path_to_map);
    break;
  } 
}