<?php
// $Id: terms_of_use.install,v 1.1.2.2 2010/04/12 15:57:21 karst Exp $

/**
 * @file
 * Terms of Use install file.
 */

/**
 * Implementation of hook_uninstall().
 */
function terms_of_use_uninstall() {
  // Delete variables.
  variable_del('terms_of_use_node_title');
  variable_del('terms_of_use_fieldset_name');
  variable_del('terms_of_use_checkbox_label');
  variable_del('terms_of_use_node_id');
}

