<?php

include_once('newplay_mapping.features.inc');

function newplay_mapping_nodeapi(&$node, $op) {
}


/**
 * Implementation of hook_form_alter
 */
function newplay_mapping_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {
    $form['filter_reset'] = array(
      '#type' => 'markup',
      '#value' => l(t('Show All Results'), '', array(
        'attributes' => array(
          'id' => 'filter_reset'
        ),
        // Add all the required query strings
        // This triggers various things such as showing results and showing all pins
        'query' => array(
          'play' => 'All',
          'event_type' => 'All',
          'theater' => 'All',
          'partner_org' => 'All',
          'org_type' => 'All',
          'budget' => 'All',
          'nat_mem' => 'All',
          'interests' => 'All',
          'artist' => 'All'
        )
      ))
    );
  }
}