<?php

include_once('general.features.inc');

/** 
 * Implementation of hook_menu().
 */
function general_menu() {
  $items = array();
  $items['welcome-links'] = array(
    'title' => 'Welcome links',
    'page callback' => 'general_welcome_links_data',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  $items['monitor'] = array(
    'title' => 'Monitor Page',
    'page callback' => 'general_monitor',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function general_welcome_links_data() {
  global $user;
  $welcome_text = '';
  if($user->uid != 0){
    $welcome_text .=  '<span class="welcome">' . t('Welcome') . ', ' . $user->name . '!</span>';
    $welcome_text .=  '<span class="my-account"><a href="participate/user">My Account</a></span>';
    $welcome_text .=  '<span class="logout"><a href="participate/logout">Sign out</a></span>';
  }else{
    $welcome_text .=  '<span class="welcome">' . t('Welcome') . '!</span>';
    $welcome_text .=  '<span class="login"><a href="participate/user">Sign in</a> or <a href="participate/user/register">Register</a></span>';
  }

  echo $welcome_text;
}

function general_monitor() {
  echo 'success';
}

/**
 * Implementation of hook_user()
 */
function general_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'login':
      drupal_goto('http://' . $_SERVER['HTTP_HOST'] . str_replace('/participate/', '', base_path()));
    break;
    case 'logout':
      drupal_goto('http://' . $_SERVER['HTTP_HOST'] . str_replace('/participate/', '', base_path()));
    break;
  }
}