<?php

include_once('plays_and_events.features.inc');

/**
 * Implementation of hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * args, contexts, content_types. In this case the subdirectories of
 * taxonomy_content/panels are used.
 */
function plays_and_events_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implementation of hook_form_alter()
 */
function plays_and_events_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'event_node_form') {
    // Hide the artist membership field (leave it for admins so we don't forget it's there)
    $form['field_event_desc']['#access'] = user_access('administer nodes');
  }
  
}